name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Due to unupdated mirrors, we will temporary switch to this method
      # - name: Setup Zig
      #   uses: mlugg/setup-zig@v1
      #   with:
      #     version: master
      - name: Setup Zig
        run: |
          wget https://ziglang.org/download/0.16.0/zig-x86_64-linux-0.16.0.tar.xz
          tar -xf zig-x86_64-linux-0.16.0.tar.xz
          echo "$GITHUB_WORKSPACE/zig-x86_64-linux-0.16.0" >> $GITHUB_PATH

      - name: Run Tests
        run: zig build test --summary all

      - name: Check Release Build (Windows x86_64)
        run: zig build -Dtarget=x86_64-windows -Doptimize=ReleaseSafe

      - name: Check Release Build (Linux x86_64)
        run: zig build -Dtarget=x86_64-linux-gnu -Doptimize=ReleaseSafe

